### ISSUE TITLE
Indicate versions of VirtualBox that are compatible with Vagrant, and that virtualization must be enabled

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_vagrant#108]
Some lessons learned from helping people at iCamp: some laptops don't have virtualization turned on in the BIOS, and VirtualBox's most recent version, 5.1, is not compatible with Vagrant (oldest is 5.0.x).

We should update the README to include these tips.

**Comment by DonRichards** [comment]
Merged
