### ISSUE TITLE
GSearch authorization in README.md is incorrect

### ISSUE THREAD

**Issue by shauntru** [Islandora-Labs/islandora_vagrant#113]
I tried to sign in to the GSearch webservice at http://localhost:8080/fedoragsearch/rest and the authorizations listed in the README (username: fgsAdmin password: fgsAdmin) didn't work. 

It turns out after some trial and error that the username and password listed for Fedora in the README did allow me to sign into GSearch (username: fedoraAdmin password: fedoraAdmin)

**Comment by DonRichards** [comment]
Looks like you're right. Thanks for pointing that out. I'll create a pull request now and I'll add URLs for the Fedora.

**Comment by DonRichards** [comment]
Looks like you're right. Thanks for pointing that out. I'll create a pull request now and I'll add URLs for the Fedora.

**Comment by DonRichards** [comment]
Merged. Thanks @shauntru for pointing this out

**Comment by shauntru** [comment]
No problem!
