### ISSUE TITLE
Permissions for anonymous user

### ISSUE THREAD

**Issue by DonRichards** [Islandora-Labs/islandora_vagrant#120]
Not able to get to the collections as anonymous user. I think this might be confusing for the on-boarding process. This is a simple change. Would anyone be interested in it?

**Comment by lutaylor** [comment]
Would we want to add "Search the Solr index" as well if we are adding rights to view fedora objects?

**Comment by DonRichards** [comment]
https://github.com/Islandora-Labs/islandora_vagrant/pull/121
