### ISSUE TITLE
Documentation on manual testing

### ISSUE THREAD

**Issue by bryjbrown** [Islandora-Labs/islandora_vagrant#122]
Each module that has a .travis.yml file in it is running certain tests via drush coder-review (`drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora_module_name`), but I can't get this same command to run inside of islandora_vagrant. Running the command outputs the following error:
```
Release standards, Drupal Security Checks, Drupal Coding Standards, Internationalization, Drupal CodeSniffer

PHP Fatal error:  Access level to Drupal_Sniffs_Functions_DiscouragedFunctionsSniff::$forbiddenFunctions must be public (as in class Generic_Sniffs_PHP_ForbiddenFunctionsSniff) in /var/www/drupal/sites/all/modules/coder/coder_sniffer/Drupal/Sniffs/Functions/DiscouragedFunctionsSniff.php on line 20
Drush command terminated abnormally due to an unrecoverable error.                                                                                                     [error]
Error: Access level to Drupal_Sniffs_Functions_DiscouragedFunctionsSniff::$forbiddenFunctions must be public (as in class Generic_Sniffs_PHP_ForbiddenFunctionsSniff)
in /var/www/drupal/sites/all/modules/coder/coder_sniffer/Drupal/Sniffs/Functions/DiscouragedFunctionsSniff.php, line 20
```

I keep failing Travis reviews for things like trailing whitespace so I'd love to be able to check for this stuff myself before sending it to Travis. Can we add a testing section to the islandora_vagrant README about how to run the Travis checks manually?

**Comment by DonRichards** [comment]
This sounds good! I'll look into it.

**Comment by DonRichards** [comment]
@bryjbrown I was able to run this in islandora_vagrant without any errors. 

Is this the steps you're using?

```terminal
$ cd /var/www/drupal
$ drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora_scholar
....
sites/all/modules/islandora_scholar/modules/pmid/xsl/exslt/date/functions/week-in-year/date.js:
 +66: [normal] do not use mixed case (camelCase), use lower case and _
 +114: [normal] do not use mixed case (camelCase), use lower case and _
 +132: [normal] do not use mixed case (camelCase), use lower case and _
 +168: [normal] do not use mixed case (camelCase), use lower case and _
 +194: [normal] do not use mixed case (camelCase), use lower case and _...
...

Status Messages:
Coder found 1 projects, 330 files, 542 normal warnings, 0 warnings were flagged to be ignored
Coder found 1 projects, 330 files, 542 normal warnings, 0 warnings were flagged to be ignored 

[status]

Drush command terminated abnormally due to an unrecoverable error
```

And from what I've read the last line `Drush command terminated abnormally due to an unrecoverable error` is because of how the command exits and is not an actual error.

**Comment by DonRichards** [comment]
Something to note, you will always have to run it from within `/var/www/drupal/`. In fact I've experienced issue with some drupal commands from operating from within a child directory.

**Comment by bryjbrown** [comment]
I think that this must have occured at a time when codesniffer was broken or misconfigured, and that time has since passed. I totally forgot about this issue and have been running `drush coder-review` many times lately without issue. You can close this.

**Comment by DonRichards** [comment]
No problem. Thanks!
