### ISSUE TITLE
Add PHPENV (or some simple way to switch PHP versions for testing)

### ISSUE THREAD

**Issue by bryjbrown** [Islandora-Labs/islandora_vagrant#124]
I'm trying to test a bug that only shows up in PHP7. Would be nice to have a CLI util for switching the global PHP version to make troubleshooting easier.

**Comment by lutaylor** [comment]
Please see discussion here https://github.com/Islandora-Labs/islandora_vagrant_base_box/issues/28

PHP7 unfortunately would mean switching to Ubuntu 16.04. It has been proposed to roll a seperate vagrant box that runs the newer ubuntu and PHP7.

**Comment by DonRichards** [comment]
This needs to happen at the base box version I believe. Related issue https://github.com/Islandora-Labs/islandora_vagrant_base_box/issues/28

**Comment by DonRichards** [comment]
@bryjbrown I'd like to close this if there's no community interest.

**Comment by DonRichards** [comment]
1 yr now response, I think it's safe to close.
