### ISSUE TITLE
Included GhostScript version (9.10) fails to extract PDF pages on RGB format

### ISSUE THREAD

**Issue by bondjimbond** [Islandora-Labs/islandora_vagrant#127]
See https://jira.duraspace.org/browse/ISLANDORA-2035

I've had this problem in my production repository using 9.10, and running tests in Vagrant, discovered that it also has v. 9.10 and the same issue.

Extracting TIFFs from PDFs (in, for example, a newspaper issue PDF ingest) fails to create TIFF OBJ files when using RGB image format, meaning all derivative creation for the objects fails. Changing to GhostScript 9.05 fixes the issue. discoverygarden identified the problem for us.

Tested in Vagrant using this PDF: http://lc.arcabc.ca/islandora/object/lc%3A2003/datastream/PDF/view

First test settings: 48-bit RGB, 150 DPI or 300 DPI (extraction fails)
Second test: 32-bit CMYK, 300 DPI (extraction succeeds)

**Comment by DonRichards** [comment]
That's an interesting find but GhostScript version isn't assigned from vagrant. But you created a ticket for it in Jira so that's the right place to start. I'm on the committers call and I will make sure it's discussed then as well. I'm going to close this ticket for now unless you believe it should be addressed here as well?

**Comment by lutaylor** [comment]
The version being installed is coming from the Ubuntu repos. 

Something like this will work:
```
wget http://downloads.ghostscript.com/public/old-gs-releases/ghostscript-9.05.tar.gz
tar xvzf ghostscript-9.05.tar.gz
cd ghostscript-9.05
./configure
make && make install

gs --version
#should return result

```
However, it is a really old version.

**Comment by DonRichards** [comment]
@lutaylor Do you think this might be a syntax issue that can be corrected within the Islandora code?
An example of something similar is with ffmpeg. If we upgrade to the latest version you have to drop one of the switches it uses in the video solution pack because it's no longer needed. I'm think this might be the case again.

**Comment by lutaylor** [comment]
@DonRichards 
I think some of the switches were deprecated. We likely have to modify this to accommodate newer versions: 
https://github.com/Islandora/islandora_solution_pack_pdf/blob/7.x/includes/derivatives.inc#L153

**Comment by DiegoPino** [comment]
@bondjimbond can you confirm that all 9.10 versions fail? I see two: Which is quite recent
https://launchpad.net/ubuntu/+source/ghostscript/9.10~dfsg-0ubuntu10.10

and https://launchpad.net/ubuntu/+source/ghostscript/9.10~dfsg-0ubuntu10
which was the original one from 2014.

Wonder if the first (security update) produced this?

**Comment by bondjimbond** [comment]
@DiegoPino I'd love to attempt it, but I've no idea how to change my GhostScript version. What's the procedure?

**Comment by DiegoPino** [comment]
@bondjimbond could be tricky. First, you need to remove the new one:
```Shell
sudo apt-get --purge remove ghostscript
```
Then you need to force libgs to that version and then (-f optional) go for the original ghostscript
```Shell
sudo apt-get install libgs9=9.10~dfsg-0ubuntu10
sudo apt-get install -f ghostscript=9.10~dfsg-0ubuntu10
```

Quite a lot of issues lately on newer ghostscript release...

**Comment by DonRichards** [comment]
Just so I'm completely clear on how to replicate this. @bondjimbond 

1. Ingest 2 newspapers (ideally multiple pages)
   - Using TIFFs images
     - 1st newspaper TIFFs should be RGB (to fail)
     - 2nd newspaper TIFFs should be CMYK (to pass)
2. Check if derivatives were properly generated
3. Follow Diego's instructions (reverting to GhostScript version 9.05)
4. Run the first 2 steps again to see if RGB passes. 

Does this sound about right?

**Comment by bondjimbond** [comment]
@DonRichards Close. Ingest using PDFs, not TIFFs. GhostScript extracts TIFFs from the PDFs. You can use the PDF linked in the original comment for testing.

**Comment by bondjimbond** [comment]
@DiegoPino Sorry, I missed your comment while I was on vacation. I see some other stuff relating to GS has gone through... do you still need me to confirm whether other versions fail?

**Comment by DonRichards** [comment]
@bondjimbond so to revise my question

1. Ingest 2 newspapers (ideally multiple pages)
   - Using a PDF
     - 1st newspaper PDF should use the PAGE IMAGE SETTINGS at the upload page of 48-bit RGB, 150 DPI or 300 DPI with Extract text from the PDF
     - 2nd newspaper PDF should use the PAGE IMAGE SETTINGS at the upload page of 32-bit CMYK, 300 DPI with Extract text from the PDF
2. Check if derivatives were properly generated
3. Follow Diego's instructions (reverting to GhostScript version 9.05)
4. Run the first 2 steps again to see if RGB passes. 

Screenshot to help with.
![screenshot-localhost-8000-2017-09-20-15-39-11-802](https://user-images.githubusercontent.com/2738244/30663840-f00a8124-9e19-11e7-9ed7-1a63e09abffb.png)

**Comment by bondjimbond** [comment]
@DonRichards Looks good!

**Comment by DonRichards** [comment]
Hmm.... I'm rebuilding, I just saw this merged PR from a few days ago. https://github.com/Islandora/islandora_paged_content/pull/137/files#diff-2d69368f59ba81d5635cd8274dd66090R1181

**Comment by csqrs** [comment]
FYI, Ghostscript 9.18, default under Ubuntu 16, produces no errors and good output
for the following commands (taken from 'islandora_paged_content', the
'islandora_paged_content_extract_tiff_from_pdf' function):

gs -q -dNOPAUSE -dBATCH -sDEVICE=tiff48nc -sCompression=none -sOutputFile=tst-300-48-p1.tiff -r300dpi -dFirstPage=1 -dLastPage=2 sample-multipage.pdf

gs -q -dNOPAUSE -dBATCH -sDEVICE=tiff48nc -sCompression=none -sOutputFile=tst-150-48-p1.tiff -r150dpi -dFirstPage=1 -dLastPage=2 sample-multipage.pdf

The output is RGB format. Using the 'tiff64nc' device produces CMYK format output, also with
no error.

The sample multipage pdf was this: https://lc.arcabc.ca/islandora/object/lc:2626/datastream/PDF/download.

**Comment by lutaylor** [comment]
http://git.ghostscript.com/?p=ghostpdl.git;h=2001f469b539a5ccce301ace5d6384b6b7e46888 it wasn't included till Ghostscript 9.12 https://www.ghostscript.com/pipermail/gs-cvs/2014-March/017368.html the highest version in 14.04 is 9.10.

**Comment by lutaylor** [comment]
@csqrs 
Looks like it was actually fixed under https://github.com/Islandora/islandora_paged_content/commit/723004bb732d171ae7ad49f994878cc454641629 still doesn't allow compression however for older versions. 

We could just use https://github.com/Islandora-Labs/islandora_vagrant_base_box/pull/32 to avoid having to go without compression https://github.com/Islandora/islandora_paged_content/blob/7.x/includes/utilities.inc#L1193-L1198

@DonRichards as mentioned in PR this is optional either way we could look at closing out this issue.

**Comment by DonRichards** [comment]
OK, looking at it momentarily.
