### ISSUE TITLE
Can we rename the main branch to 7.x?

### ISSUE THREAD

**Issue by rosiel** [Islandora-Labs/islandora_vagrant#135]
Right now it's "master" which is the git default, but it's not very expressive, and it's different from all our other repos. 

Is there a way to rename it without breaking current "installations" and, if not, would it be worth doing anyway?

**Comment by DonRichards** [comment]
I was thinking about this recently. I think it's a good idea to be consistent with the rest of the community

**Comment by DonRichards** [comment]
I just put in a PR to merge 1.10 into master then I'll address this ticket.

**Comment by rosiel** [comment]
@DiegoPino @DonRichards should we consider this again - now that vagrant is getting its release-time checkup? I still got confused because there's a 'master' and a '7.x' branch that's a little behind. 

Is it possible to rename a remote branch and cause anyone formerly tracking master to now track 7.x?

**Comment by DonRichards** [comment]
@rosiel What I can do is create a new branch from master (7.x) and make it the default. And for a while keep the default(master) but add some a warning somewhere that the master branch is deprecated. Thoughts?

**Comment by DonRichards** [comment]
OK, this has been done to avoid confusion.
