### ISSUE TITLE
Add the bells and whistles to a special branch 

### ISSUE THREAD

**Issue by DonRichards** [Islandora-Labs/islandora_vagrant#151]
How about a branch that includes everything, not just Islandora but also Islandora-labs modules with examples. 

Like: 
* islandora_bibliography
* islandora_simple_map
* islandora_solution_pack_oralhistories
* islandora_usage_stats_callbacks
* islandora_social_metatags
* islandora_ip_embargo
* etc

Would this be useful? Is this even possible?

**Comment by bryjbrown** [comment]
I would personally find it useful (especially if it came with some example objects).

It can certainly be done as a separate branch, but I'd want to hear arguments why this shouldn't be the main branch.

**Comment by mjordan** [comment]
If it included https://github.com/mjordan/islandora_scg we could run some drush commands to populate the default collections. But, not all users will want to do that so anything that creates sample objects should probably be optional.

**Comment by DonRichards** [comment]
@bryjbrown My only concern is release testing. During a new release this is expected behave in a precise way for testing with only core code. Introducing islandora-labs modules **could** be problematic. I have no solid examples of when this could cause problems. I'm just siding on the side of caution. Perhaps we first do this as a branch and if everyone agrees we could always merge it into the 7.x branch?

**Comment by bryjbrown** [comment]
@DonRichards Sounds like a solid plan to me. 

@mjordan +1 to including https://github.com/mjordan/islandora_scg

**Comment by lutaylor** [comment]
@DonRichards 
Sounds like a good idea. Should we consider it "open" as in we can add modules to the branch as requested? 

It should be possible as long as it remains an upstream branch. We shouldn't be able to merge to the main branches from it.

**Comment by DonRichards** [comment]
What would you guys like the branch name to be? Any Suggestions?

**Comment by bryjbrown** [comment]
@DonRichards How about "7.x-contrib"? My understanding of "contrib" in the context of open source projects is that it contains tools which are supplementary to a project, but not core, which is exactly what we are trying to signal here.

**Comment by DonRichards** [comment]
I like it. Anyone else want to +1 Bryan's suggestion? @lutaylor @mjordan

**Comment by lutaylor** [comment]
@DonRichards 
@bryjbrown 
Sounds good to me

**Comment by DonRichards** [comment]
OK, thanks! I'll create the branch and we can casually start working on that.
