### ISSUE TITLE
Support for Flash ended on December 31, 2020.

### ISSUE THREAD

**Issue by bjarman** [Islandora-Labs/islandora_vagrant#167]
Hi! I just installed islandora_vagrant on my local machine. When trying to view http://localhost:8080/fedora/admin/ I get this information:

Alternate HTML content should be placed here. This content requires the Adobe Flash Player. Get Flash

However, since flash EOL was 2020 I can no longer find and install the flash plugin. Is there another UI for the fedora/admin?

Best regards/Fredrik

**Comment by mjordan** [comment]
@bjarman are you specifically interested in Islandora 7.x? Islandora 2 (aka Islandora 8) is now the current version. The equivalent Vagrant-based installation for Islandora 2 is https://github.com/Islandora-Devops/islandora-playbook. Documentation for Islandora 2 is at https://islandora.github.io/documentation/.

Islandora 2 uses a modern version of Fedora that doesn't rely on a Flash admin interface.

**Comment by bjarman** [comment]
Thank you for this information. I will use the playbook instead.
