### ISSUE TITLE
Using Features within custom.sh

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_vagrant#69]
This isn't an enhancement issue, I thought I'd document something cool and potentially useful to others.

I've been playing with [Features](https://www.drupal.org/project/features) (and the accompanying [Strongarm](https://www.drupal.org/project/strongarm) module). Basically, you use these two modules to dump out various site configurations into a module, move the module to another Drupal instance, enable the module, and then 'revert' the configuration expressed in the module on the new site. In my custom.sh script, I download and enable Features and Strongarm, then clone the module that contains the dumped features configuration, then run the drush command to revert that configuration into the Vagrant site:

```
cd /var/www/drupal/sites/all/modules
drush en features -y
drush en strongarm -y
# This is a git repo containing the dumped out features module
git clone http://git.example.com/example/islandora_test_site.git
# Enable the module
drush --yes en islandora_test_site
# Apply the 'feature' to the site
drush --yes features-revert islandora_test_site
```

Combined with automating the loading of some sample content, we'll find this ability very useful for testing and training VMs.

**Comment by DonRichards** [comment]
Is this a complete set of instructions from within your example code? Should this live in the README?

**Comment by DonRichards** [comment]
Is this the same as Islandora Sample Content Generator?
Should we invest the time to add a custom script and put this on it? It would be a good example of what could be done. 

Or should we close this for now?

**Comment by DonRichards** [comment]
@mjordan OK, looking at this with fresh eyes and I think I completely missed the point. I see now. Do you still feel this would be useful (I do)?

**Comment by mjordan** [comment]
@DonRichards blast from the past. We used Features quite a bit preparing for our migration, but since then I haven't used them much on the Vagrant. So I'm OK with closing this.

**Comment by DonRichards** [comment]
lol, thanks
